sudo: false
branches:
  only:
    - master
language: python
python:
  - 3.4
before_install:
  - pip install --upgrade pip
  - pip --version
install: make env
script: make test
notifications:
  email: false
